services:
  vasm:
    build:
      context: .
      dockerfile: docker/Dockerfile.vasm
    volumes:
      - .:/workspace
    working_dir: /workspace    

  minipro:
    build:
      context: .
      dockerfile: docker/Dockerfile.minipro
    volumes:
      - .:/workspace
      - /dev/bus/usb:/dev/bus/usb
    working_dir: /workspace
    privileged: true    

  ca65:
    build:
      context: .
      dockerfile: docker/Dockerfile.cc65
    volumes:
      - .:/workspace
    working_dir: /workspace
    privileged: true

  ld65:
    build:
      context: .
      dockerfile: docker/Dockerfile.cc65
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ["/opt/cc65/bin/ld65"]
    privileged: true